### PR TITLE
Edits to description and some reordering

### PR DESCRIPTION
**Pull request by charlottenosam**
- added some more description/maths about constructing posteriors
- renamed a few parameters to make definitions clearer
- reordered initialization of ensemble sampler to be in same cell as `run_mcmc` so that only one set of samples are run (previously every time `run_mcmc` cell ran new samples were added, which gets confusing when looking at chains...)

### CODE REVIEW

**Comment by griffin-h** [comment]
This is great, thank you! Would you mind resetting the notebooks and recommitting them to get rid of the changed metadata (execution time, etc.)? You should also add yourself as an author at the top!

**Comment by charlottenosam** [comment]
Will do. Do you know how to remove the metadata without losing the output of the cells?

**Comment by griffin-h** [comment]
I think for the solutions you just want to restart the kernel (but not restart & clear output). There might still be changed metadata about what version of Python you used, but that's unavoidable.

For the tutorial notebooks, you do want to restart & clear output.

**Comment by charlottenosam** [comment]
ok, hopefully fixed. The execution time thing is coming from my nbextensions and I can't see any easy way to clear that (even without it activated...) 😬 anyway did it manually, should be cleaned up now.

**Pull request merged**
